Repository GreenBlitz/GB-Robot-Template, pull requests merged in 2024-05, with the labels that each got.

#45 yoav - System Identification
  src/main/java/frc/utils/calibration/sysid/SysIdCalibrator.java
  src/main/java/frc/utils/calibration/sysid/SysIdConstants.java
  src/main/java/frc/utils/loggerutils/LoggerConstants.java
  src/main/java/frc/utils/loggerutils/LoggerUtils.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests, no-need-of-simulation-testing

#100 yoav - Auto Static Characterization
  src/main/java/frc/robot/simulation/ElevatorSimulation.java
  src/main/java/frc/robot/simulation/FlywheelSimulation.java
  src/main/java/frc/robot/simulation/MotorSimulation.java
  src/main/java/frc/robot/simulation/SimpleMotorSimulation.java
  src/main/java/frc/robot/simulation/SingleJointedArmSimulation.java
  src/main/java/frc/utils/calibration/staticcharacterization/FindKg.java
  src/main/java/frc/utils/calibration/staticcharacterization/FindKs.java
  src/main/java/frc/utils/calibration/staticcharacterization/StaticCharacterizationConstants.java
  src/main/java/frc/utils/calibration/staticcharacterization/StaticCharacterizationObject.java
  src/main/java/frc/utils/roborioutils/RoborioUtils.java
  src/main/java/frc/utils/roborioutils/RoborioUtilsConstants.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests, no-need-of-simulation-testing

#117 yoav - Constants Protected
  src/main/java/frc/utils/calibration/sysid/SysIdConstants.java
  src/main/java/frc/utils/joysticks/AxisButton.java
  src/main/java/frc/utils/joysticks/SmartJoystickConstants.java
  src/main/java/frc/utils/loggerutils/LoggerConstants.java
  src/main/java/frc/utils/roborioutils/RoborioUtilsConstants.java
Labels: A-SMALL-PR, clean, no-need-of-robot-testing, no-need-of-simulation-testing

#99 Hillel - Implement choreo (3 files)
  Choreo.chor
  src/main/deploy/pathplanner/navgrid.json
  vendordeps/ChoreoLib.json
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#111 hillel - adding autonomous selector (3 files)
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/utils/AutonomousSelector.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#118 yoav - Fixed Master
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/utils/AutonomousSelector.java
Labels: fix-bug, A-SMALL-PR, passed-all-tests

#120 yoav - Spotless
  .scripts/pre-commit
  .vscode/launch.json
  .vscode/settings.json
  .wpilib/wpilib_preferences.json
  build.gradle
  src/main/deploy/pathplanner/navgrid.json
  src/main/java/frc/robot/simulation/ElevatorSimulation.java
  src/main/java/frc/robot/simulation/FlywheelSimulation.java
  src/main/java/frc/robot/simulation/GyroSimulation.java
  src/main/java/frc/robot/simulation/MotorSimulation.java
  src/main/java/frc/robot/simulation/SimpleMotorSimulation.java
  src/main/java/frc/robot/simulation/SingleJointedArmSimulation.java
  src/main/java/frc/utils/calibration/staticcharacterization/FindKs.java
  src/main/java/frc/utils/calibration/sysid/SysIdCalibrator.java
  src/main/java/frc/utils/commands/ExecuteEndCommand.java
  src/main/java/frc/utils/commands/InitExecuteCommand.java
  src/main/java/frc/utils/devicewrappers/TalonFXWrapper.java
  src/main/java/frc/utils/loggerutils/LoggerUtils.java
  src/main/java/frc/utils/roborioutils/RoborioUtils.java
  vendordeps/AdvantageKit.json
  vendordeps/ChoreoLib.json
  vendordeps/PathPlannerLib.json
  vendordeps/Phoenix5.json
  vendordeps/Phoenix6.json
  vendordeps/REVLib.json
  vendordeps/WPILibNewCommands.json
Labels: feature-creation, A-BIG-PR, passed-all-tests, no-need-of-robot-testing

#116 yoav - Battery Util
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/robot/constants/SimulationConstants.java
  src/main/java/frc/robot/simulation/MotorSimulation.java
  src/main/java/frc/utils/batteryutils/Battery.java
  src/main/java/frc/utils/batteryutils/BatteryConstants.java
  src/main/java/frc/utils/batteryutils/BatteryLimiter.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests, no-need-of-simulation-testing

#121 yoav - Battery Status
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/utils/batteryutils/Battery.java
  src/main/java/frc/utils/batteryutils/BatteryConstants.java
  src/main/java/frc/utils/batteryutils/BatteryLimiter.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#115 yoav - Odometry Thread
  src/main/java/frc/robot/poseestimation/poseestimator/PoseEstimatorConstants.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModule.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModuleConfigObject.java
  src/main/java/frc/robot/subsystems/swerve/odometryThread/OdometryThreadConstants.java
  src/main/java/frc/robot/subsystems/swerve/odometryThread/PhoenixOdometryThread6328.java
  src/main/java/frc/robot/subsystems/swerve/swervegyro/pigeon2swervegyro/Pigeon2SwerveGyro.java
  src/main/java/frc/robot/subsystems/swerve/swervegyro/pigeon2swervegyro/Pigeon2SwerveGyroConfigObject.java
Labels: feature-creation, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#122 yoav - Pose estimator
  src/main/java/frc/robot/JoysticksBindings.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/poseestimation/poseestimator/PoseEstimator.java
  src/main/java/frc/robot/poseestimation/poseestimator/PoseEstimator6328.java
  src/main/java/frc/robot/poseestimation/poseestimator/PoseEstimatorConstants.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveCommands.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
  src/main/java/frc/robot/subsystems/swerve/modules/Module.java
  src/main/java/frc/robot/subsystems/swerve/modules/ModuleConstants.java
  src/main/java/frc/robot/subsystems/swerve/modules/simulationmodule/SimulationModule.java
  src/main/java/frc/utils/joysticks/AxisButton.java
  src/main/java/frc/utils/joysticks/SmartJoystick.java
Labels: feature-creation, A-MEDIUM-PR, passed-all-tests

#123 yoav - Fix Pre Commit
  .scripts/pre-commit
Labels: fix-bug, A-SMALL-PR, passed-all-tests

#126 yoav - Improve Spotless
  .scripts/pre-commit
Labels: feature-improvment, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#128 yoav - Clean
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/simulation/FlywheelSimulation.java
  src/main/java/frc/robot/simulation/SingleJointedArmSimulation.java
  src/main/java/frc/utils/DriverStationUtils.java
  src/main/java/frc/utils/batteryutils/Battery.java
  src/main/java/frc/utils/batteryutils/BatteryLimiter.java
  src/main/java/frc/utils/joysticks/AxisButton.java
  src/main/java/frc/utils/joysticks/SmartJoystick.java
  src/main/java/frc/utils/loggerutils/LoggerUtils.java
  src/main/java/frc/utils/roborioutils/RoborioUtils.java
  src/main/java/frc/utils/roborioutils/RoborioUtilsConstants.java
  src/main/java/frc/utils/utilcommands/DashboardCommand.java
  src/main/java/frc/utils/utilcommands/ExecuteEndCommand.java
  src/main/java/frc/utils/utilcommands/InitExecuteCommand.java
Labels: A-SMALL-PR, clean, no-need-of-robot-testing, no-need-of-simulation-testing

#125 yoav - Alliance Rotation and Translation
  src/main/java/frc/utils/allianceutils/AlliancePose2d.java
  src/main/java/frc/utils/allianceutils/AllianceRotation2d.java
  src/main/java/frc/utils/allianceutils/AllianceTranslation2d.java
  src/main/java/frc/utils/allianceutils/AllianceUtils.java
Labels: A-SMALL-PR, passed-all-tests

#124 Swerve state
  src/main/java/frc/robot/JoysticksBindings.java
  src/main/java/frc/robot/constants/FieldConstants.java
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/robot/poseestimation/poseestimator/PoseEstimator.java
  src/main/java/frc/robot/poseestimation/poseestimator/PoseEstimatorConstants.java
  src/main/java/frc/robot/subsystems/swerve/DriveMode.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveCommands.java
  src/main/java/frc/robot/subsystems/swerve/SwerveState.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModuleConstants.java
  src/main/java/frc/robot/subsystems/swerve/swervegyro/SwerveGyroConstants.java
  src/main/java/frc/robot/subsystems/swerve/swervegyro/pigeon2swervegyro/Pigeon2SwerveGyro.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/AimAssist.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/DriveMode.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/DriveSpeed.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/LoopMode.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/RotateAxis.java
  src/main/java/frc/utils/allianceutils/AlliancePose2d.java
  src/main/java/frc/utils/allianceutils/AllianceRotation2d.java
Labels: feature-improvment, A-BIG-PR, passed-all-tests

#130 yoav - Atan Function
  src/main/java/frc/robot/JoysticksBindings.java
  src/main/java/frc/robot/constants/MathConstants.java
  src/main/java/frc/robot/subsystems/swerve/SwerveCommands.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/RotateAxis.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#134 yoav - Improve and Clean master
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/Autos.java
  src/main/java/frc/robot/commands/ExampleCommand.java
  src/main/java/frc/robot/constants/FieldConstants.java
  src/main/java/frc/robot/constants/LogPathsConstants.java
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/robot/subsystems/ExampleSubsystem.java
  src/main/java/frc/utils/DriverStationUtils.java
  src/main/java/frc/utils/GBSubsystem.java
  src/main/java/frc/utils/batteryutils/Battery.java
  src/main/java/frc/utils/mirrorutils/MirrorablePose2d.java
  src/main/java/frc/utils/mirrorutils/MirrorableTranslation3d.java
  src/main/java/frc/utils/roborioutils/RoborioUtils.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, clean

#137 yoav - State Improvment
  src/main/java/frc/robot/JoysticksBindings.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveCommands.java
  src/main/java/frc/robot/subsystems/swerve/SwerveState.java
Labels: feature-improvment, A-BIG-PR, passed-all-tests

#138 yoav - Added Pigeon
  src/main/java/frc/utils/devicewrappers/Pigeon2Wrapper.java
Labels: feature-improvment, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#136 yoav - Pro GBSubsys (add to master to)
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/utils/GBSubsystem.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#139 Subsys improv
  src/main/java/frc/utils/GBSubsystem.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#140 yoav - Joystick Functions
  src/main/java/frc/utils/joysticks/SmartJoystick.java
  src/main/java/frc/utils/joysticks/SmartJoystickConstants.java
Labels: feature-improvment, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#141 yoav - naming
  src/main/java/frc/utils/joysticks/SmartJoystick.java
Labels: A-SMALL-PR, clean, no-need-of-robot-testing, no-need-of-simulation-testing

#143 yoav - Logged Dashboard Command
  src/main/java/frc/utils/utilcommands/DashboardCommand.java
  src/main/java/frc/utils/utilcommands/LoggedDashboardCommand.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#145 Things of Swerve
  src/main/java/frc/robot/subsystems/swerve/modules/ModuleConstants.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModuleActions.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModuleConstants.java
  src/main/java/frc/robot/subsystems/swerve/modules/simulationmodule/SimulationModuleActions.java
Labels: A-BIG-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#147 yoav - clean
  src/main/java/frc/robot/Robot.java
Labels: A-SMALL-PR, passed-all-tests, clean, no-need-of-robot-testing

#149 yoav - clean
  src/main/java/frc/utils/DriverStationUtils.java
  src/main/java/frc/utils/batteryutils/BatteryLimiter.java
Labels: A-SMALL-PR, clean, no-need-of-robot-testing, no-need-of-simulation-testing

#108 yoav - Wheel Radius Characterization
  src/main/java/frc/utils/calibration/swervecalibration/WheelRadiusCharacterization.java
  src/main/java/frc/utils/calibration/swervecalibration/WheelRadiusConstants.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#148 yoav - Toggle Constants
  .editorconfig
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/robot/constants/ToggleConstants.java
  src/main/java/frc/utils/DriverStationUtils.java
  src/main/java/frc/utils/batteryutils/BatteryLimiter.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#150 yoav - removed Toggle Constants
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/robot/constants/ToggleConstants.java
  src/main/java/frc/utils/DriverStationUtils.java
  src/main/java/frc/utils/batteryutils/BatteryLimiter.java
Labels: fix-bug, A-SMALL-PR, passed-all-tests

#152 yoav - Visual Vm
  build.gradle
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#155 yoav - conflicts?
  src/main/java/frc/robot/simulation/ElevatorSimulation.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#157 yoav - Fix
  .github/workflows/compile.yml
  src/main/java/frc/robot/simulation/ElevatorSimulation.java
Labels: A-SMALL-PR, clean, no-need-of-robot-testing, no-need-of-simulation-testing

#159 yoav - Solved Warnings In Compile
  .github/workflows/compile.yml
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#160 yoav - Fast Compile
  build.gradle
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#161 yoav - Candevice
  src/main/java/frc/utils/CTREUtils/CTREDeviceID.java
  src/main/java/frc/utils/CTREUtils/PhoenixProUtils.java
Labels: feature-creation, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#162 yoav - Clean CtreDeviceID
  src/main/java/frc/utils/CTREUtils/CTREDeviceID.java
  src/main/java/frc/utils/devicewrappers/TalonFXWrapper.java
Labels: feature-improvment, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#163 yoav - Add ctreID
  src/main/java/frc/robot/constants/Ports.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModuleConfigObject.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModuleConstants.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#167 yoav - Rio Utils Improvment
  src/main/java/frc/robot/simulation/ElevatorSimulation.java
  src/main/java/frc/robot/simulation/FlywheelSimulation.java
  src/main/java/frc/robot/simulation/SimpleMotorSimulation.java
  src/main/java/frc/robot/simulation/SingleJointedArmSimulation.java
  src/main/java/frc/utils/calibration/staticcharacterization/FindKg.java
  src/main/java/frc/utils/calibration/staticcharacterization/FindKs.java
  src/main/java/frc/utils/roborioutils/RoborioUtils.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing
