Repository GreenBlitz/GB-Robot-Template, pull requests merged in 2024-09, with the labels that each got.

#330 Kinematics -> swerve
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/poseestimation/PoseEstimator.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveCommandsBuilder.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
  src/main/java/frc/robot/subsystems/swerve/factories/swerveconstants/RealSwerveConstants.java
  src/main/java/frc/robot/subsystems/swerve/factories/swerveconstants/SimulationSwerveConstants.java
  src/main/java/frc/robot/subsystems/swerve/modules/Module.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/SwerveStateHelper.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#331 Generate Constants -> swerve
  src/main/java/frc/robot/subsystems/swerve/factories/gyro/GyroFactory.java
  src/main/java/frc/robot/subsystems/swerve/factories/gyro/RealGyroConstants.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/drive/DriveRealConstants.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/encoder/EncoderFactory.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/encoder/EncoderRealConstants.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/steer/SteerRealConstants.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/steer/SteerSimulationConstants.java
Labels: A-SMALL-PR, passed-all-tests

#333 Unlog PP -> swerve
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#334 Radius Calibration -> swerve
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveCommandsBuilder.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#335 Thread -> swerve
  src/main/java/frc/robot/subsystems/swerve/gyro/pigeon2/Pigeon2ThreadedGyro.java
  src/main/java/frc/robot/subsystems/swerve/modules/drive/talonfx/TalonFXDrive.java
  src/main/java/frc/robot/subsystems/swerve/modules/steer/talonfx/TalonFXSteer.java
  src/main/java/frc/robot/subsystems/swerve/phoenix6signalsthread/Phoenix6SignalsThreadConstants.java
  src/main/java/frc/utils/ctre/Phoenix6SignalsThread.java
Labels: A-SMALL-PR, clean, no-need-of-robot-testing, no-need-of-simulation-testing

#338 clean
  src/main/java/frc/utils/ComputerLogFile.java
  src/main/java/frc/utils/devicewrappers/TalonFXWrapper.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#332 Different Arrays Lengths -> swerve
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/modules/Module.java
  src/main/java/frc/robot/subsystems/swerve/modules/Modules.java
Labels: fix-bug, A-SMALL-PR, passed-all-tests

#336 Power Distribution Device ID -> core
  src/main/java/frc/robot/constants/IDs.java
  src/main/java/frc/utils/battery/BatteryConstants.java
  src/main/java/frc/utils/battery/BatteryUtils.java
  src/main/java/frc/utils/battery/PowerDistributionDeviceID.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#337 SparkMax Device ID -> core
  src/main/java/frc/utils/devicewrappers/SparkMaxDeviceID.java
  src/main/java/frc/utils/devicewrappers/SparkMaxWrapper.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#340 Remove Closed Loop Reference -> core
  src/main/java/frc/robot/simulation/MotorSimulation.java
Labels: fix-bug, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#344 CheckWithRetry Returns StatusCode -> core
  src/main/java/frc/utils/ctre/PhoenixProUtils.java
Labels: A-SMALL-PR, passed-all-tests

#318 Brake State -> core
  src/main/java/frc/robot/RobotManager.java
  src/main/java/frc/utils/brakestate/BrakeStateManager.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#234 Update PathPlannerLib -> pp-dev
  vendordeps/PathPlannerLib.json
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#346 Naming
  src/main/java/frc/utils/Conversions.java
Labels: no-need-of-robot-testing, no-need-of-simulation-testing

#341 Connected Input -> core
  src/main/java/frc/robot/hardware/ConnectedInput.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#283 Alert -> core
  src/main/java/frc/robot/RobotManager.java
  src/main/java/frc/robot/constants/LogPaths.java
  src/main/java/frc/utils/alerts/Alert.java
  src/main/java/frc/utils/alerts/AlertManager.java
  src/main/java/frc/utils/alerts/PeriodicAlert.java
  src/main/java/frc/utils/battery/BatteryConstants.java
  src/main/java/frc/utils/battery/BatteryLimiter.java
  src/main/java/frc/utils/ctre/BusChain.java
  src/main/java/frc/utils/cycletime/CycleTimeConstants.java
  src/main/java/frc/utils/cycletime/CycleTimeUtils.java
  src/main/java/frc/utils/logger/LoggerFactory.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#236 Path planner util -> pp-dev
  src/main/java/frc/robot/RobotManager.java
  src/main/java/frc/utils/auto/PathPlannerUtils.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#351 Current Simulation -> core
  src/main/java/frc/robot/simulation/ElevatorSimulation.java
  src/main/java/frc/robot/simulation/FlywheelSimulation.java
  src/main/java/frc/robot/simulation/MotorSimulation.java
  src/main/java/frc/robot/simulation/SimpleMotorSimulation.java
  src/main/java/frc/robot/simulation/SingleJointedArmSimulation.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#348 Beam Breaker -> core
  src/main/java/frc/utils/digitalinput/DigitalInputInputs.java
  src/main/java/frc/utils/digitalinput/IDigitalInput.java
  src/main/java/frc/utils/digitalinput/channeled/ChanneledDigitalInput.java
  src/main/java/frc/utils/digitalinput/chooser/ChooserDigitalInput.java
  src/main/java/frc/utils/digitalinput/supplied/SuppliedDigitalInput.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#350 Request, PhoenixRequest -> core
  src/main/java/frc/robot/hardware/request/IRequest.java
  src/main/java/frc/robot/hardware/request/phoenix6/Phoenix6AngleRequest.java
  src/main/java/frc/robot/hardware/request/phoenix6/Phoenix6DoubleRequest.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#352 Phoenix Regular Signals -> core
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6AngleSignal.java
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6BothLatencySignal.java
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6DoubleSignal.java
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6LatencySignal.java
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6SignalBuilder.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#325 Limelights but fixed to posestimator
  src/main/java/frc/robot/constants/Field.java
  src/main/java/frc/robot/poseestimator/limelights/Limelight.java
  src/main/java/frc/robot/poseestimator/limelights/LimelightEntryValue.java
  src/main/java/frc/robot/poseestimator/limelights/LimelightRawData.java
  src/main/java/frc/robot/poseestimator/limelights/MultiLimelightsRawData.java
  src/main/java/frc/robot/poseestimator/limelights/VisionConstants.java
  src/main/java/frc/robot/poseestimator/limelights/VisionObservationFiltered.java
  src/main/java/frc/robot/poseestimator/limelights/VisionObservationFilteredConfig.java
Labels: needs-robot-testing, feature-creation, A-SMALL-PR, no-need-of-simulation-testing

#361 Organize
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
Labels: bug-fix, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#364 Package -> core
  src/main/java/frc/robot/hardware/digitalinput/DigitalInputInputs.java
  src/main/java/frc/robot/hardware/digitalinput/IDigitalInput.java
  src/main/java/frc/robot/hardware/digitalinput/channeled/ChanneledDigitalInput.java
  src/main/java/frc/robot/hardware/digitalinput/chooser/ChooserDigitalInput.java
  src/main/java/frc/robot/hardware/digitalinput/supplied/SuppliedDigitalInput.java
  src/main/java/frc/utils/digitalinput/IDigitalInput.java
Labels: A-SMALL-PR, clean, no-need-of-robot-testing, no-need-of-simulation-testing

#362 Sysid -> core
  src/main/java/frc/utils/calibration/sysid/SysIdCalibrator.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#366 Packaging+naming -> core
  src/main/java/frc/robot/RobotManager.java
  src/main/java/frc/robot/hardware/phoenix6/BusChain.java
  src/main/java/frc/robot/hardware/phoenix6/Phoenix6DeviceID.java
  src/main/java/frc/robot/hardware/phoenix6/PhoenixProUtils.java
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6SignalBuilder.java
  src/main/java/frc/utils/ctre/CTREDeviceID.java
  src/main/java/frc/utils/devicewrappers/Pigeon2Wrapper.java
  src/main/java/frc/utils/devicewrappers/TalonFXWrapper.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#360 Phoenix6 Device -> core
  src/main/java/frc/robot/hardware/EmptyDevice.java
  src/main/java/frc/robot/hardware/IDevice.java
  src/main/java/frc/robot/hardware/phoenix6/Phoenix6Device.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#363 Gyro -> device
  src/main/java/frc/robot/RobotManager.java
  src/main/java/frc/robot/hardware/gyro/EmptyGyro.java
  src/main/java/frc/robot/hardware/gyro/IGyro.java
  src/main/java/frc/robot/hardware/gyro/phoenix6/Pigeon2Gyro.java
  src/main/java/frc/robot/hardware/gyro/phoenix6/Pigeon2Wrapper.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests, no-need-of-simulation-testing

#353 IAngleEncoder, EmptyAngleEncoder & CANCoderEncoder -> core
  src/main/java/frc/robot/hardware/angleencoder/CANCoderEncoder.java
  src/main/java/frc/robot/hardware/angleencoder/EmptyAngleEncoder.java
  src/main/java/frc/robot/hardware/angleencoder/IAngleEncoder.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#371 USB_ALERT -> core
  src/main/java/frc/utils/logger/LoggerFactory.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#374 Line Length -> core
  codestyle.xml
  src/main/java/frc/robot/Main.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotManager.java
  src/main/java/frc/robot/hardware/digitalinput/supplied/SuppliedDigitalInput.java
  src/main/java/frc/robot/hardware/gyro/phoenix6/Pigeon2Wrapper.java
  src/main/java/frc/robot/hardware/phoenix6/BusChain.java
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6BothLatencySignal.java
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6LatencySignal.java
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6SignalBuilder.java
  src/main/java/frc/utils/Conversions.java
  src/main/java/frc/utils/calibration/sysid/SysIdCalibrator.java
  src/main/java/frc/utils/devicewrappers/TalonFXWrapper.java
  src/main/java/frc/utils/utilcommands/LoggedDashboardCommand.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#365 Motor -> core
  src/main/java/frc/robot/hardware/motor/Controllable.java
  src/main/java/frc/robot/hardware/motor/ControllableMotor.java
  src/main/java/frc/robot/hardware/motor/IMotor.java
  src/main/java/frc/robot/hardware/motor/phoenix6/TalonFXMotor.java
  src/main/java/frc/robot/hardware/motor/phoenix6/TalonFXWrapper.java
  src/main/java/frc/robot/simulation/MotorSimulation.java
  src/main/java/frc/robot/simulation/SimulationManager.java
  src/main/java/frc/utils/devicewrappers/TalonFXWrapper.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#372 Signals Timestamps
  src/main/java/frc/robot/hardware/signal/AngleArraySignal.java
  src/main/java/frc/robot/hardware/signal/AngleSignal.java
  src/main/java/frc/robot/hardware/signal/DoubleArraySignal.java
  src/main/java/frc/robot/hardware/signal/DoubleSignal.java
  src/main/java/frc/robot/hardware/signal/InputSignal.java
  src/main/java/frc/robot/hardware/signal/TimedValue.java
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6AngleSignal.java
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6DoubleSignal.java
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6LatencySignal.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#376 tabs
  src/main/java/frc/robot/hardware/phoenix6/BusChain.java
  src/main/java/frc/robot/hardware/signal/phoenix/Phoenix6SignalBuilder.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#377 const
  Choreo.chor
  src/main/deploy/example.txt
  src/main/java/frc/robot/constants/GlobalConstants.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#379 space
  src/main/java/frc/utils/GBSubsystem.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#380 no-abs
  src/main/java/frc/utils/GBSubsystem.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#375 Sparkmaxes -> core
  src/main/java/frc/robot/RobotManager.java
  src/main/java/frc/robot/hardware/motor/sparkmax/BrushedSparkMAXMotor.java
  src/main/java/frc/robot/hardware/motor/sparkmax/BrushlessSparkMAXMotor.java
  src/main/java/frc/robot/hardware/motor/sparkmax/SparkMaxDeviceID.java
  src/main/java/frc/robot/hardware/motor/sparkmax/SparkMaxMotor.java
  src/main/java/frc/robot/hardware/motor/sparkmax/SparkMaxWrapper.java
  src/main/java/frc/robot/hardware/signal/cansparkmax/ISparkMaxSignal.java
  src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxAngleSignal.java
  src/main/java/frc/robot/hardware/signal/cansparkmax/SparkMaxDoubleSignal.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#381 fix sparkMaxWrapper
  src/main/java/frc/robot/hardware/motor/sparkmax/BrushedSparkMAXMotor.java
  src/main/java/frc/robot/hardware/motor/sparkmax/BrushlessSparkMAXMotor.java
  src/main/java/frc/robot/hardware/motor/sparkmax/SparkMaxMotor.java
Labels: bug-fix, A-SMALL-PR, passed-all-tests

#383 joysticks
  src/main/java/frc/robot/JoysticksBindings.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#382 Swerve dev -> core
  .git-blame-ignore-revs
  .gitignore
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotManager.java
  src/main/java/frc/robot/constants/Field.java
  src/main/java/frc/robot/constants/IDs.java
  src/main/java/frc/robot/poseestimation/OdometryObservation.java
  src/main/java/frc/robot/subsystems/swerve/GyroStuff.java
  src/main/java/frc/robot/subsystems/swerve/HeadingStabilizer.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveCommandsBuilder.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
  src/main/java/frc/robot/subsystems/swerve/SwerveMath.java
  src/main/java/frc/robot/subsystems/swerve/SwerveName.java
  src/main/java/frc/robot/subsystems/swerve/SwerveState.java
  src/main/java/frc/robot/subsystems/swerve/factories/gyro/GyroFactory.java
  src/main/java/frc/robot/subsystems/swerve/factories/gyro/RealGyroConstants.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/ModulesFactory.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/constants/ModuleConstantsFactory.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/constants/RealModuleConstants.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/drive/DriveFactory.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/drive/DriveRealConstants.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/encoder/EncoderFactory.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/encoder/EncoderRealConstants.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/steer/SteerFactory.java
  src/main/java/frc/robot/subsystems/swerve/factories/modules/steer/SteerRealConstants.java
  src/main/java/frc/robot/subsystems/swerve/factories/swerveconstants/RealSwerveConstants.java
  src/main/java/frc/robot/subsystems/swerve/factories/swerveconstants/SwerveConstantsFactory.java
  src/main/java/frc/robot/subsystems/swerve/modules/Module.java
  src/main/java/frc/robot/subsystems/swerve/modules/ModuleConstants.java
  src/main/java/frc/robot/subsystems/swerve/modules/ModuleUtils.java
  src/main/java/frc/robot/subsystems/swerve/modules/Modules.java
  src/main/java/frc/robot/subsystems/swerve/modules/extrainputs/DriveInputs.java
  src/main/java/frc/robot/subsystems/swerve/modules/extrainputs/ModuleInputs.java
  src/main/java/frc/robot/subsystems/swerve/modules/stuffs/DriveStuff.java
  src/main/java/frc/robot/subsystems/swerve/modules/stuffs/EncoderStuff.java
  src/main/java/frc/robot/subsystems/swerve/modules/stuffs/SteerStuff.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/AimAssist.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/AimAssistMath.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/DriveRelative.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/DriveSpeed.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/HeadingControl.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/LoopMode.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/RotateAxis.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/SwerveStateHelper.java
  src/main/java/frc/robot/superstructure/Tolerances.java
  src/main/java/frc/utils/joysticks/Axis.java
  src/main/java/frc/utils/pathplannerutils/LocalADStarAK.java
  src/main/java/frc/utils/pathplannerutils/PathPlannerUtils.java
Labels: A-BIG-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#386 Error -> core
  src/main/java/frc/robot/hardware/phoenix6/Phoenix6Device.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#389 Supplied Signal -> core
  src/main/java/frc/robot/hardware/motor/sparkmax/SparkMaxMotor.java
  src/main/java/frc/robot/hardware/signal/cansparkmax/ISparkMaxSignal.java
  src/main/java/frc/robot/hardware/signal/supplied/SuppliedAngleSignal.java
  src/main/java/frc/robot/hardware/signal/supplied/SuppliedDoubleSignal.java
Labels: feature-improvment, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing
