Repository GreenBlitz/GB-Robot-Template, pull requests merged in 2024-04, with the labels that each got.

#20 yoav - checked auto calibration
  src/main/java/frc/robot/JoysticksBindings.java
  src/main/java/frc/robot/commands/calibration/FindP.java
Labels: bug-fix, in-testing, new-feature

#26 yoav - fixed logger
  src/main/java/frc/utils/LoggerUtils.java
Labels: bug-fix, A SMALL PR, passed-all-tests

#29 yoav - Check auto commit
  build.gradle
Labels: bug-fix, A SMALL PR, passed-all-tests

#33 yoav - changed auto commit format
  build.gradle
Labels: feature-improvment, A SMALL PR, passed-all-tests

#27 yoav - Spotless (4 files)
  .vscode/launch.json
  .vscode/settings.json
  build.gradle
  src/main/java/frc/utils/GBCommand.java
Labels: feature-creation, A SMALL PR, passed-all-tests, crucial

#30 yoav - Auto Commit (1 file)
  build.gradle
Labels: feature-creation, A SMALL PR, passed-all-tests, crucial

#32 yoav - Post commit (2 files) (Don't merge)
  .scripts/post-commit
  build.gradle
Labels: waiting-for-another-pr, feature-creation, A SMALL PR, passed-all-tests, crucial

#31 yoav - Pre Commit (2 files)
  .gitignore
  .scripts/post-commit
  .scripts/pre-commit
  build.gradle
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/utils/LoggerUtils.java
  src/main/java/frc/utils/joysticks/SmartJoystick.java
Labels: waiting-for-another-pr, feature-creation, A SMALL PR, passed-all-tests, crucial

#34 yoav - pre commit
  .gitignore
  .scripts/post-commit
  .scripts/pre-commit
  build.gradle
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/utils/LoggerUtils.java
  src/main/java/frc/utils/joysticks/SmartJoystick.java
Labels: feature-creation, A MEDIUM PR, passed-all-tests

#36 yoav - added auto pull
  .scripts/post-checkout
  build.gradle
Labels: feature-creation, A SMALL PR, passed-all-tests

#37 yoav - Auto Set Upstream
  .scripts/post-commit
Labels: feature-creation, A SMALL PR, passed-all-tests

#35 yoav - Records for Subsystems (14 files)
  src/main/java/frc/robot/subsystems/swerve/gyro/gyropigeon2/GyroPigeon2.java
  src/main/java/frc/robot/subsystems/swerve/gyro/gyropigeon2/GyroPigeon2Actions.java
  src/main/java/frc/robot/subsystems/swerve/gyro/gyropigeon2/GyroPigeon2ConfigObject.java
  src/main/java/frc/robot/subsystems/swerve/gyro/gyropigeon2/GyroPigeon2Constants.java
  src/main/java/frc/robot/subsystems/swerve/gyro/gyropigeon2/GyroPigeon2Records.java
  src/main/java/frc/robot/subsystems/swerve/gyro/gyropigeon2/GyroPigeon2Status.java
  src/main/java/frc/robot/subsystems/swerve/mk4iswerve/mk4imodule/MK4IModule.java
  src/main/java/frc/robot/subsystems/swerve/mk4iswerve/mk4imodule/MK4IModuleActions.java
  src/main/java/frc/robot/subsystems/swerve/mk4iswerve/mk4imodule/MK4IModuleConfigObject.java
  src/main/java/frc/robot/subsystems/swerve/mk4iswerve/mk4imodule/MK4IModuleConstants.java
  src/main/java/frc/robot/subsystems/swerve/mk4iswerve/mk4imodule/MK4IModuleRecords.java
  src/main/java/frc/robot/subsystems/swerve/mk4iswerve/mk4imodule/MK4IModuleStatus.java
Labels: feature-improvment, waiting-for-another-pr, A MEDIUM PR, passed-all-tests

#38 yoav - removed spotlees
  .scripts/pre-commit
  build.gradle
Labels: fix-bug, A SMALL PR, passed-all-tests

#40 yoav - Delete Pose Estim
  src/main/java/frc/robot/poseestimation/PoseEstimatorFactory.java
  src/main/java/frc/robot/poseestimation/poseestimator6328/PoseEstimator6328.java
  src/main/java/frc/robot/subsystems/swerve/Module.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/simulationswerve/SimulationSwerve.java
  src/main/java/frc/robot/subsystems/swerve/simulationswerve/simulationmodule/SimulationModule.java
  src/main/java/frc/robot/subsystems/swerve/swerveinterface/ModuleInputs.java
  src/main/java/frc/robot/subsystems/swerve/swerveinterface/SwerveInputs.java
Labels: fix-bug, A SMALL PR, passed-all-tests

#41 yoav - Auto Format
  .scripts/pre-commit
Labels: fix-bug, A SMALL PR, passed-all-tests

#42 Yoav - deleted build
  .scripts/pre-commit
Labels: fix-bug, A SMALL PR, passed-all-tests

#43 yoav - Cleaned Device Wrappers
  src/main/java/frc/utils/devicewrappers/GBCANCoder.java
  src/main/java/frc/utils/devicewrappers/GBTalonFXPro.java
Labels: A SMALL PR, passed-all-tests, clean

#46 yoav - IntelIj Formater
  build.gradle
  src/main/java/frc/utils/Conversions.java
  src/main/java/frc/utils/allianceutils/AllianceUtils.java
  src/main/java/frc/utils/joysticks/SmartJoystick.java
Labels: feature-improvment, A SMALL PR, passed-all-tests, clean

#49 yoav - Init Execute and Execute End
  src/main/java/frc/utils/commands/ExecuteEndCommand.java
  src/main/java/frc/utils/commands/GBCommand.java
  src/main/java/frc/utils/commands/InitExecuteCommand.java
Labels: feature-creation, A SMALL PR, passed-all-tests

#52 yoav - Must Have "passed-all-tests"
  .github/workflows/check-passed-tests.yml
Labels: feature-creation, A SMALL PR, passed-all-tests

#53 yoav - Pre Commit -> Git Add
  .scripts/pre-commit
Labels: feature-creation, A SMALL PR, passed-all-tests

#54 yoav - Editor Settings
  .editorconfig
  .gitignore
  settings/settings.zip
Labels: feature-improvment, A SMALL PR, passed-all-tests

#63 yoav - Deleted Settings
  settings/settings.zip
Labels: A SMALL PR, passed-all-tests, clean

#61 yoav - Build Check
  .github/workflows/build.yml
Labels: A SMALL PR, passed-all-tests

#64 yoav - Label Check
  .github/workflows/check-passed-tests.yml
  .github/workflows/labels.yml
Labels: feature-improvment, A SMALL PR, passed-all-tests

#66 yoav - Auto Commit Before Build
  .github/workflows/compile.yml
  build.gradle
Labels: feature-improvment, A SMALL PR, passed-all-tests

#69 yoav - Auto Commit Naming (field -> training)
  build.gradle
Labels: A-SMALL-PR, passed-all-tests

#70 yoav - Auto Tests Labels
  .github/workflows/addTestsLabels.yml
  .github/workflows/labels.yml
Labels: A-SMALL-PR, passed-all-tests

#71 yoav -check mult
  .github/workflows/labels.yml
Labels: A-SMALL-PR, passed-all-tests

#73 yoav - Auto Label Tests
  .github/workflows/addTestsLabels.yml
  .github/workflows/labels.yml
Labels: A-SMALL-PR, passed-all-tests

#74 yoav - Labels After Push
  .github/workflows/addTestsLabels.yml
  .github/workflows/checkLabels.yml
  .github/workflows/labels.yml
Labels: feature-improvment, feature-creation, A-SMALL-PR, passed-all-tests

#76 yoav - Workflow Behavior Improvment
  .github/workflows/checkLabels.yml
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#77 yoav - No Need Testing
  .github/workflows/addTestsLabels.yml
  .github/workflows/checkLabels.yml
Labels: A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#78 yoav - Remove Post Pre Commit
  .scripts/post-commit
  .scripts/pre-commit
  build.gradle
Labels: feature-improvment, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#79 yoav - Remove Auto Commit
  build.gradle
Labels: feature-improvment, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#75 yoav - Cleaned Utils (10 files)
  src/main/java/frc/robot/constants/MathConstants.java
  src/main/java/frc/utils/Conversions.java
  src/main/java/frc/utils/GBSubsystem.java
  src/main/java/frc/utils/RobotTypeUtils.java
  src/main/java/frc/utils/allianceutils/AlliancePose2d.java
  src/main/java/frc/utils/allianceutils/AllianceUtils.java
  src/main/java/frc/utils/commands/GBCommand.java
  src/main/java/frc/utils/devicewrappers/GBTalonFXPro.java
  src/main/java/frc/utils/joysticks/SmartJoystick.java
  src/main/java/frc/utils/joysticks/SmartJoystickConstants.java
Labels: A-SMALL-PR, clean, no-need-of-robot-testing, no-need-of-simulation-testing

#80 yoav - Simulation Motor (4 files)
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/robot/simulation/MotorSimulation.java
  src/main/java/frc/robot/simulation/SimpleMotorSimulation.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#83 yoav - Set Power In Sim
  src/main/java/frc/robot/simulation/MotorSimulation.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#84 yoav- Sim Constants
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/robot/constants/SimulationConstants.java
  src/main/java/frc/robot/simulation/MotorSimulation.java
Labels: feature-improvment, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#86 yoav - GBTalonFXPro Config Constructor
  src/main/java/frc/utils/devicewrappers/GBTalonFXPro.java
Labels: feature-improvment, needs-robot-testing, A-SMALL-PR, needs-simulation-testing

#87 yoav - Elevator Simulation
  src/main/java/frc/robot/simulation/ElevatorSimulation.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#88 yoav - Arm Simulation
  src/main/java/frc/robot/simulation/ElevatorSimulation.java
  src/main/java/frc/robot/simulation/MotorSimulation.java
  src/main/java/frc/robot/simulation/SingleJointedArmSimulation.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#90 Yoav - Gyro Sim
  src/main/java/frc/robot/simulation/GyroSimulation.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#91 Flywhhel sim
  src/main/java/frc/robot/simulation/FlywheelSimulation.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#92 yoav - added cont
  src/main/java/frc/utils/devicewrappers/GBTalonFXPro.java
Labels: feature-improvment, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#95 Label imrpove
  .github/workflows/addTestsLabels.yml
  .github/workflows/checkLabels.yml
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#98 yoav - DeadBand
  src/main/java/frc/utils/joysticks/SmartJoystick.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#107 Fix labels
  .github/workflows/addTestsLabels.yml
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#109 yoav - changed formater settings
  .editorconfig
Labels: A-SMALL-PR, clean, no-need-of-robot-testing, no-need-of-simulation-testing

#81 yoav - Fixed and Improved Logger Utilization (5 files)
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/robot/constants/SimulationConstants.java
  src/main/java/frc/utils/loggerutils/LoggerConstants.java
  src/main/java/frc/utils/loggerutils/LoggerUtils.java
Labels: fix-bug, feature-improvment, A-SMALL-PR, passed-all-tests

#85 yoav - Roborio Utils
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/constants/LogPathsConstants.java
  src/main/java/frc/robot/constants/SimulationConstants.java
  src/main/java/frc/robot/simulation/ElevatorSimulation.java
  src/main/java/frc/robot/simulation/FlywheelSimulation.java
  src/main/java/frc/robot/simulation/MotorSimulation.java
  src/main/java/frc/robot/simulation/SimpleMotorSimulation.java
  src/main/java/frc/robot/simulation/SingleJointedArmSimulation.java
  src/main/java/frc/utils/roborioutils/RoborioUtils.java
  src/main/java/frc/utils/roborioutils/RoborioUtilsConstants.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests
