Repository GreenBlitz/GB-Robot-Template, pull requests merged in 2024-06, with the labels that each got.

#170 Swerve improvments
  src/main/java/frc/robot/poseestimation/poseestimator/PoseEstimator.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModuleConfigObject.java
Labels: A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#173 yoav - Fix Hooks
  build.gradle
Labels: fix-bug, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#174 yoav - Design Scripts
  .scripts/post-checkout
  .scripts/pre-commit
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, no-need-of-robot-testing

#172 yoav - CTREDevice Improvment
  src/main/java/frc/robot/constants/Phoenix6Constants.java
  src/main/java/frc/utils/CTREUtils/CTREDeviceID.java
  src/main/java/frc/utils/devicewrappers/TalonFXWrapper.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#176 yoav - Naming
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/utils/batteryutils/BatteryLimiter.java
Labels: A-SMALL-PR, clean, no-need-of-robot-testing, no-need-of-simulation-testing

#175 GREENBLITZ
  GREENBLITZ4590.png
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#180 yoav - fix
  src/main/java/frc/robot/JoysticksBindings.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModule.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModuleConstants.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#181 yoav - fix Modulu
  src/main/java/frc/robot/simulation/GyroSimulation.java
  src/main/java/frc/utils/devicewrappers/Pigeon2Wrapper.java
Labels: fix-bug, A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#151 yoav - Sysid Swerve Calibration
  src/main/java/frc/robot/JoysticksBindings.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveCommands.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
  src/main/java/frc/robot/subsystems/swerve/modules/Module.java
  src/main/java/frc/robot/subsystems/swerve/modules/ModuleConstants.java
  src/main/java/frc/robot/subsystems/swerve/modules/ModuleUtils.java
  src/main/java/frc/robot/subsystems/swerve/modules/ReplayModule.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModule.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModuleActions.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModuleConstants.java
  src/main/java/frc/robot/subsystems/swerve/modules/moduleinterface/IModule.java
  src/main/java/frc/robot/subsystems/swerve/modules/moduleinterface/ModuleInputs.java
  src/main/java/frc/robot/subsystems/swerve/modules/simulationmodule/SimulationModule.java
  src/main/java/frc/robot/subsystems/swerve/modules/simulationmodule/SimulationModuleActions.java
  src/main/java/frc/robot/subsystems/swerve/modules/simulationmodule/SimulationModuleConstants.java
Labels: feature-creation, A-SMALL-PR, passed-all-tests

#164 yoav - Bus Status (using ctre)
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/simulation/ElevatorSimulation.java
  src/main/java/frc/robot/simulation/FlywheelSimulation.java
  src/main/java/frc/robot/simulation/MotorSimulation.java
  src/main/java/frc/robot/simulation/SimpleMotorSimulation.java
  src/main/java/frc/robot/simulation/SingleJointedArmSimulation.java
  src/main/java/frc/utils/CTREUtils/CANStatus.java
  src/main/java/frc/utils/Conversions.java
  src/main/java/frc/utils/calibration/staticcharacterization/FindKg.java
  src/main/java/frc/utils/calibration/staticcharacterization/FindKs.java
  src/main/java/frc/utils/cycletimeutils/CycleTimeConstants.java
  src/main/java/frc/utils/cycletimeutils/CycleTimeUtils.java
  src/main/java/frc/utils/loggerutils/LoggerConstants.java
  src/main/java/frc/utils/roborioutils/RoborioUtils.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, no-need-of-simulation-testing

#182 yoav - PID Rotation
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
Labels: A-SMALL-PR, passed-all-tests

#183 yoav - State Improvement
  src/main/java/frc/robot/constants/RobotConstants.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/DriveMode.java
  src/main/java/frc/robot/subsystems/swerve/swervestatehelpers/RotateAxis.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#184 Cmd
  build.gradle
  src/main/java/frc/utils/applicationsutils/CMDHandler.java
  src/main/java/frc/utils/applicationsutils/OnDeploy.java
Labels: A-SMALL-PR, passed-all-tests

#186 Cmd
  src/main/java/frc/utils/applicationsutils/CMDHandler.java
  src/main/java/frc/utils/applicationsutils/OnDeploy.java
Labels: A-SMALL-PR, passed-all-tests

#188 yoav
  src/main/java/frc/utils/calibration/staticcharacterization/FindKg.java
  src/main/java/frc/utils/calibration/staticcharacterization/FindKs.java
  src/main/java/frc/utils/calibration/staticcharacterization/StaticCharacterizationConstants.java
  src/main/java/frc/utils/calibration/staticcharacterization/StaticCharacterizationObject.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#144 yoav - Coupling
  src/main/java/frc/robot/subsystems/swerve/modules/Module.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModule.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModuleActions.java
  src/main/java/frc/robot/subsystems/swerve/modules/mk4imodule/MK4IModuleConstants.java
  src/main/java/frc/robot/subsystems/swerve/modules/moduleinterface/ModuleInputs.java
  src/main/java/frc/robot/subsystems/swerve/modules/simulationmodule/SimulationModule.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests, no-need-of-simulation-testing

#190 yoav - fix docs
  src/main/java/frc/utils/calibration/sysid/SysIdCalibrator.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#191 yoav: ADD This.
  src/main/java/frc/utils/joysticks/SmartJoystick.java
Labels: A-SMALL-PR, no-need-of-robot-testing, no-need-of-simulation-testing

#195 yoav: Paths To Logger
  src/main/java/frc/utils/loggerutils/LogSaveSpot.java
  src/main/java/frc/utils/loggerutils/LoggerConstants.java
  src/main/java/frc/utils/loggerutils/LoggerUtils.java
Labels: feature-improvment, A-SMALL-PR, passed-all-tests

#200 Better CMD
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/simulation/MotorSimulation.java
  src/main/java/frc/utils/applicationsutils/CMDHandler.java
  src/main/java/frc/utils/applicationsutils/OnDeploy.java
Labels: A-SMALL-PR, passed-all-tests, no-need-of-robot-testing
